color: null
fieldLayouts:
  d57ac6dc-43ba-489b-b941-45071924e811:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0d0cb0e9-c0a7-4093-9d6f-6b1e894d35b3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08f0c8e2-e9c0-426a-aab3-861fbf413a1f # Heading
            handle: null
            instructions: null
            label: Title
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d78fb25-bc9e-451d-857c-ab3814ee8541
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 39a76ad9-6746-4fb7-be42-bd92bcd72610 # Answers
            handle: null
            instructions: null
            label: Content
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c948c664-6e91-416c-ab52-86bc37708785
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6e043019-db2b-4996-8b2d-7490ae3c8d9c
        userCondition: null
handle: accordions
hasTitleField: false
icon: circle-question
name: Accordions
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
