color: null
fieldLayouts:
  8c6fe932-8e72-4bab-ad68-835a08aa00e4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9b1a133a-4d4f-4a24-bb40-e59834fea921 # Container
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8406c64-e516-4ca7-984b-af575ef919b5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f5fb7721-061b-4515-a589-5e5a87619514
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5d2385da-c451-4d15-a8dc-9bf204cfb717 # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad88c30a-4bab-467b-8729-d3445adc6a0f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 08f0c8e2-e9c0-426a-aab3-861fbf413a1f # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96030288-e2c7-4b78-9110-e5f944771eeb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 28f860da-7e14-4288-a55f-bce3b2856d85 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd925fc2-3189-4fee-917e-241ca10e9cd1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3d1f10a-2e4d-40dc-9dc4-d6aea55b51d7 # Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8dd8d261-af44-4c55-98f1-5a413a31c530
            userCondition: null
            warning: null
            width: 100
        name: Auxiliary
        uid: bec52014-43a1-4d36-a232-8a31f5ded348
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            elementCondition: null
            heading: 'Block Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 8dc1f7dd-22c1-4f8d-b96e-79033c409c71
            userCondition: null
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeac151d-d4a9-4733-9c2f-c8a1eac9a41b # Content Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d880f979-1dac-4de1-a0b8-cc70fa96bcd9
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-09-26T05:25:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6f38b25f-efca-4db5-b007-cd3fed523fdd # Minus Margin Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bed36afb-591f-4a36-a838-250965e01147
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c54b7104-c058-41f4-ac16-278920cf8062 # Container Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e59a4050-47fa-4d5c-8bc3-c5c56c1c90bb
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-26T23:13:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8addc211-26f4-4d0a-ba64-f41374221fe8 # Container Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b51f46e-be08-42e0-8fac-50053e444b6e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6065b222-611d-42ce-a1de-85a02891694c # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aadd6cf6-3899-4b16-9d03-2f9bc4f1830e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f36b49ea-9938-42fb-9803-9772a378f173 # Overlay Opacity
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5049883-6736-4182-9c43-a2fa79441d31
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            elementCondition: null
            heading: 'Content Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 44aad9b4-3545-4438-8edf-00f3e77960e4
            userCondition: null
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cfc164dd-7161-4a3d-9407-1080228e7455 # Content Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cca7d785-35dc-4844-a1a3-4dac3c3aa76e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e05fb8e0-726b-4a55-b97f-aea98a58c8a1 # Heading Size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79f340a9-bf17-47c9-b74b-43d37779c9ab
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ef7dff82-7ddc-453d-b03e-6b90683f02bd # Font Weight
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77ad1daf-4028-4c93-bec0-b21762de839c
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d07b18ad-639f-4d5c-a587-00aec5c39f40
            userCondition: null
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d07b837d-c20e-48d9-ac52-34b7a29fbfcb # Container Id
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8c14eb2-b0e1-4825-a514-4d3984875c48
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 3f6b6029-fba4-4bdf-8360-d6e73f4c3a5e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 24e627ff-4926-4819-9fc1-9efb83576180 # Margin Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c857ab44-854e-4d5a-b181-5a98d2ac88d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d3ab5ad8-585b-43bc-b8ad-c093a04c787f # Minus Margin Top (Deprecated)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88f32648-e40d-4368-8a57-5f318128ba3f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 721f6c59-d353-4810-9d84-eee327f296be # Minus Margin Bottom (Deprecated)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5409523f-2889-4a2c-8cc2-fe2d1696a5cf
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3c47ca9b-8c91-4cdf-8e22-512525eb6f7e
            userCondition: null
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bcbc592a-d4d0-4afa-92b6-458504f09b17 # Margin Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be2e7393-be4b-44f4-afe3-f92b422a501b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9affc432-fe49-4e90-96ea-be5425095c2c # Margin Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 995b0bbe-2431-43bf-b72f-0f544fa1df3e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3c44034a-42a6-4e12-a863-4f3cc325f1a4 # Padding Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64c796bc-4e05-415d-8118-7e16c3616471
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-24T07:34:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 18de2689-3603-4c37-8473-396f9ce4f78c # Padding Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11089654-b9cb-4655-9790-b13936d8528f
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: dd1fec42-1308-4f24-9dce-3b5167770331
        userCondition: null
handle: container
hasTitleField: false
icon: toolbox
name: Container
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
