color: null
fieldLayouts:
  f5ebb72c-959e-4283-b74f-630d6e18c738:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 02179733-968a-4c8a-a812-71edce9f1c0f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b15cab4-22ae-40f3-9612-204b951f30f0 # Image
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1761bd7e-bbf5-466e-b210-4cb94a40a6ea
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 7f018fb5-73a1-482a-97e6-20b925125348 # Videos
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8bca20c-24c4-48ab-acda-82491963378f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 020945fa-5674-4ed6-a075-6eead7271143
            userCondition: null
          -
            elementCondition: null
            fieldUid: 5d2385da-c451-4d15-a8dc-9bf204cfb717 # Eyebrow
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38a9536c-d24b-44f5-9904-3202b1faa5a0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08f0c8e2-e9c0-426a-aab3-861fbf413a1f # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e321c93-4de3-4439-83c7-f1bdf08a2976
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28f860da-7e14-4288-a55f-bce3b2856d85 # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51612203-0a21-45b7-a1cf-9f59438d91f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3d1f10a-2e4d-40dc-9dc4-d6aea55b51d7 # Buttons
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 589d959c-a2bf-4f71-9204-b8a316396aa4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c428799a-9479-44b4-a0b9-0bc1b24e6a86
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            heading: 'Content Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 36329240-7434-4687-be5f-8cb75573e585
            userCondition: null
          -
            elementCondition: null
            fieldUid: aeac151d-d4a9-4733-9c2f-c8a1eac9a41b # Content Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aeea8ea3-c0b7-4163-bd4b-62b6b076798a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6065b222-611d-42ce-a1de-85a02891694c # Background Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b928c2c0-4fed-42e0-8d0e-9c5e9093f7d5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f36b49ea-9938-42fb-9803-9772a378f173 # Overlay Opacity
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ab220b9-840d-4055-b26d-cc2685a47556
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Block Settings'
            type: craft\fieldlayoutelements\Heading
            uid: 1525caf1-00ff-4add-8fc5-82b2d39a7ac3
            userCondition: null
          -
            elementCondition: null
            fieldUid: cfc164dd-7161-4a3d-9407-1080228e7455 # Content Alignment
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7d811ba-624b-4996-8298-213499ab5744
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e05fb8e0-726b-4a55-b97f-aea98a58c8a1 # Heading Size
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 406769c9-07ba-41d3-b044-5d4e95451b67
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: ef7dff82-7ddc-453d-b03e-6b90683f02bd # Font Weight
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa652562-e916-4d26-8a91-23aa34be545b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0461720f-dd70-496b-9474-c235bb7684ae
            userCondition: null
          -
            elementCondition: null
            fieldUid: d07b837d-c20e-48d9-ac52-34b7a29fbfcb # Container Id
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92d512f7-06b6-49b1-9f64-17a489013b03
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: a1d2b1fc-3661-4ec0-80b2-4a63e70141b7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d3ab5ad8-585b-43bc-b8ad-c093a04c787f # Minus Margin Top (Deprecated)
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d83c1cb-29a2-43e9-92ea-a5891d433740
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 721f6c59-d353-4810-9d84-eee327f296be # Minus Margin Bottom (Deprecated)
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc9d4c30-acc4-40b2-910a-8d3b0cb6aa9e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 9b071c93-4917-45a0-a231-30dc8ce0c896
            userCondition: null
          -
            elementCondition: null
            fieldUid: bcbc592a-d4d0-4afa-92b6-458504f09b17 # Margin Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b40466a-ece8-412b-8969-1544c79da3b5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9affc432-fe49-4e90-96ea-be5425095c2c # Margin Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd63bfaf-b518-46f8-9f7c-9c9f38dd5141
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3c44034a-42a6-4e12-a863-4f3cc325f1a4 # Padding Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f486deb-c179-4baa-a9ad-1892ce6efb7f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 18de2689-3603-4c37-8473-396f9ce4f78c # Padding Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d5d4093-ca19-4ba0-903a-dbd998d143cd
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: a02a34ed-85b9-4371-a88c-361fbd500ab6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 21102308-0ca8-4b67-8663-daef265f4c60 # Animation?
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccaed5c8-82ab-4ed1-85df-76790df2bea1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 8b3d4661-0d16-4c34-9f8c-f10704f397c0
            userCondition: null
          -
            elementCondition: null
            fieldUid: 3b2d250a-efd7-4394-9e59-a1ae3b9d5292 # Animation Style
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfc98720-3e44-40ef-b705-3ef52a5de11a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8df78e11-4ebe-4815-a6a8-a9a62e77b6d6 # Animation Easing
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58969853-c8b3-4528-92e2-cd8abb178006
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e0e47b5e-62b4-4b02-aeca-99868e8625d9 # Animation Duration
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08c4f8fb-2d8e-4742-a35d-59367e64ae1e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0e13a17a-1829-4ccb-a64f-c39b6d62af82 # Animation Offset
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5fee452-581f-4314-90f5-409fa9b9bed5
            userCondition: null
            warning: null
            width: 50
        name: Animation
        uid: f34e760c-89b9-4e99-bc6f-9775ab02b836
        userCondition: null
handle: featuredBanner
hasTitleField: false
icon: flag-pennant
name: 'Featured Banner'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
