color: null
fieldLayouts:
  0f6e8e2e-36e9-4f48-8aec-16a18bbce31c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0b15cab4-22ae-40f3-9612-204b951f30f0 # Image
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14d55189-e98b-4102-ba5f-d138198a8f67
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f018fb5-73a1-482a-97e6-20b925125348 # Videos
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6f5be73-3cf7-425a-b67a-d5a89c3bb2fd
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 021cf0d0-1863-4788-aeb4-6225da5b03a9 # Embed Video
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b663c952-e0ac-4aa4-b9fa-2a7611372234
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7d09c5e7-e849-465a-9e4f-087bdef82bb4 # Caption
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f89febd3-662d-445b-9f3a-7a83b3c4fe5c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 16fadc98-a390-402a-80d7-8234998b0aa6
        userCondition: null
      -
        elementCondition: null
        name: Auxiliary
        uid: b9f55bc1-531e-4446-a9ce-94297697e750
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            elementCondition: null
            heading: 'Block Settings'
            type: craft\fieldlayoutelements\Heading
            uid: dba4dfbf-cd84-4402-a674-ff68535b2e7e
            userCondition: null
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeac151d-d4a9-4733-9c2f-c8a1eac9a41b # Content Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dbb44c8-1fdc-462a-a3bd-04e1ee95777b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c54b7104-c058-41f4-ac16-278920cf8062 # Container Size
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2ebcac8-9799-46d2-948b-dc81593b6e88
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9ce08183-1391-4b24-8288-a39ac4f97186 # Image Ratio
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 678eb606-2c47-466e-8050-f4a972d8f222
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6065b222-611d-42ce-a1de-85a02891694c # Background Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de0f3a00-052e-47be-a00c-5dd7d85775d6
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f36b49ea-9938-42fb-9803-9772a378f173 # Overlay Opacity
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adeb6324-1565-4e49-9174-fd59e006a69d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 71fa55a9-c465-4fe2-91f2-ee5a739774a9 # Overlay Gradient
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17b53dfb-48fd-4f8a-b69d-c0010a2e950a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            elementCondition: null
            heading: 'Content Settings'
            type: craft\fieldlayoutelements\Heading
            uid: ca585044-84a5-43a4-a30b-e547facc6f77
            userCondition: null
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cfc164dd-7161-4a3d-9407-1080228e7455 # Content Alignment
            handle: captionAlignment
            instructions: null
            label: 'Caption Alignment'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee732823-6955-4255-9413-ff9338768d7d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 1ce5a3bd-7431-4030-97da-0209668f61eb
            userCondition: null
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d07b837d-c20e-48d9-ac52-34b7a29fbfcb # Container Id
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ed0d7f2-81e4-46f6-91b4-cf9c0f2a1475
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 611c7b00-a291-43c1-aad8-08bcb8988781
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d3ab5ad8-585b-43bc-b8ad-c093a04c787f # Minus Margin Top (Deprecated)
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d49c430b-f618-4004-9f02-c544b03d08e4
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 721f6c59-d353-4810-9d84-eee327f296be # Minus Margin Bottom (Deprecated)
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfe98f46-49d9-4181-a699-b2f7a85a5088
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 138352be-3fe4-4857-ae59-2bc774e9f975
            userCondition: null
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bcbc592a-d4d0-4afa-92b6-458504f09b17 # Margin Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd8c1614-872b-46cc-9651-417810503499
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9affc432-fe49-4e90-96ea-be5425095c2c # Margin Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba4bb77c-5af0-4589-ae69-8b8cd6f3c73b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3c44034a-42a6-4e12-a863-4f3cc325f1a4 # Padding Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d00528eb-5d97-4b94-b583-f82b1a304bba
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 18de2689-3603-4c37-8473-396f9ce4f78c # Padding Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf48afb4-1d74-49d3-8514-2a3cb928225d
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: 8476de66-edb9-4c23-9e26-dd815bacff71
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 21102308-0ca8-4b67-8663-daef265f4c60 # Animation?
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b40e1cb5-6adf-426c-838c-ea7ee106347c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: e4a94e0f-459e-41f2-8ba2-9f854bb1858d
            userCondition: null
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3b2d250a-efd7-4394-9e59-a1ae3b9d5292 # Animation Style
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aedfd6e1-b1a1-4372-88cd-d794b11a1449
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8df78e11-4ebe-4815-a6a8-a9a62e77b6d6 # Animation Easing
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c829f05-9c36-419d-8ecd-88e9338ba3c7
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e0e47b5e-62b4-4b02-aeca-99868e8625d9 # Animation Duration
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ebd85bf-3667-41ef-820e-932ad1204cea
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-27T06:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0e13a17a-1829-4ccb-a64f-c39b6d62af82 # Animation Offset
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6df16646-005b-47ae-9408-7feedd45fdd6
            userCondition: null
            warning: null
            width: 50
        name: Animation
        uid: 7073b338-7d5b-4e0b-a0e9-1180906c2900
        userCondition: null
handle: image
hasTitleField: false
icon: image
name: Image
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
