color: null
fieldLayouts:
  45c434b4-451e-4a14-8eea-924170e0c19e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9c8462aa-4a2f-4942-b602-20a7ec687c94
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ae7d75d-cf9a-41db-b14d-a11c5a609f43 # Icon
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d60642c4-0495-45ea-8fd9-b1a2081b2be0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d2385da-c451-4d15-a8dc-9bf204cfb717 # Eyebrow
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abafc6f9-99d0-409a-adeb-8ad4653360f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08f0c8e2-e9c0-426a-aab3-861fbf413a1f # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 249ea569-f91e-451f-9287-b79a1b5de47d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28f860da-7e14-4288-a55f-bce3b2856d85 # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e54f5d7-4b37-4be1-a291-342b1e6cb5bd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3d1f10a-2e4d-40dc-9dc4-d6aea55b51d7 # Buttons
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6455e69-87f7-4931-a239-628a99bbe75a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c4754ec9-ab2b-4ab0-9411-4b60ffd312eb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 14cf885b-68f2-4ea2-8f07-4a707cc2677f # Info Box Layout
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b7a009a-1d28-4ca8-8480-d46bf95e3ff7
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 14cf885b-68f2-4ea2-8f07-4a707cc2677f # Info Box Layout
                  layoutElementUid: 4b7a009a-1d28-4ca8-8480-d46bf95e3ff7
                  operator: ni
                  uid: f8785786-7aa6-4594-b8ec-a22fac0049b1
                  values:
                    - layout1
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: f9be8226-8b11-4ea4-8950-2dbcb61beec5 # Column Alignment
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e218f9c-9797-4551-b6e6-9d42538bc2ad
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: aeac151d-d4a9-4733-9c2f-c8a1eac9a41b # Content Width
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d729de66-437b-45b9-b468-59586fbfe276
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: c54b7104-c058-41f4-ac16-278920cf8062 # Container Size
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c82581ed-da7a-4521-9a3a-f9edcae1d4b3
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6065b222-611d-42ce-a1de-85a02891694c # Background Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7320a38-fa02-4f89-99d2-1acdf271fe43
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f36b49ea-9938-42fb-9803-9772a378f173 # Overlay Opacity
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 007cf5ef-dd4b-4ca0-949c-686b50818db3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 02c1f367-dcb0-49f9-af0b-e255d2928b19 # Show Border?
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8a891f4-5fa1-45ac-8124-c36c967dca94
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 02c1f367-dcb0-49f9-af0b-e255d2928b19 # Show Border?
                  layoutElementUid: b8a891f4-5fa1-45ac-8124-c36c967dca94
                  uid: 6f129205-a6be-471f-b0bb-68a0b8b0a521
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 89cc861f-51a9-49de-9637-831af3da0e7a # Border Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2d5346c-70e3-4e0f-ab9c-5cacbb5087bc
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 02c1f367-dcb0-49f9-af0b-e255d2928b19 # Show Border?
                  layoutElementUid: b8a891f4-5fa1-45ac-8124-c36c967dca94
                  uid: 5d54f915-3da6-4cae-a75e-9660e63b133d
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 26c9ce02-0df9-486a-90b7-104efcd7f5a8 # Content Box Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7889ab0-d6ff-450a-a0cb-64b0f2eaf2ed
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 2ae64850-b9cb-470a-9708-4ed7b9491a4d
            userCondition: null
          -
            elementCondition: null
            fieldUid: cfc164dd-7161-4a3d-9407-1080228e7455 # Content Alignment
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07bff6f2-15ee-4ae3-9330-d58056d554ac
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e05fb8e0-726b-4a55-b97f-aea98a58c8a1 # Heading Size
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ba707a7-5744-45a9-b7a7-2a57e61e8e4d
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: ef7dff82-7ddc-453d-b03e-6b90683f02bd # Font Weight
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 560724c2-110d-4451-8a2a-4fa251dd2235
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 61b05516-3c49-4664-adaf-d39f49485498
            userCondition: null
          -
            elementCondition: null
            fieldUid: d07b837d-c20e-48d9-ac52-34b7a29fbfcb # Container Id
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8bdd7a74-a74c-45b4-ac3a-cb7f5033a70b
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 00653883-95a5-4568-87c1-fe5742459b54
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d3ab5ad8-585b-43bc-b8ad-c093a04c787f # Minus Margin Top (Deprecated)
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 069a5213-627f-456d-8a22-3e990eefe0b1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 721f6c59-d353-4810-9d84-eee327f296be # Minus Margin Bottom (Deprecated)
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9b04472-d16c-43a5-b0b7-9eeac43752a1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: a3df0750-78b1-42fd-ab82-b60e2d6703b6
            userCondition: null
          -
            elementCondition: null
            fieldUid: bcbc592a-d4d0-4afa-92b6-458504f09b17 # Margin Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 841b38e1-3778-4179-854f-a1a25d37ec25
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9affc432-fe49-4e90-96ea-be5425095c2c # Margin Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea114efe-81c3-4ee0-a83b-23b5aca279c3
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3c44034a-42a6-4e12-a863-4f3cc325f1a4 # Padding Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ace562c4-9a53-43a7-95b6-3ff0bdc382cb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 18de2689-3603-4c37-8473-396f9ce4f78c # Padding Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92b21321-1dcb-4fbd-8c67-f64e2741a98a
            userCondition: null
            warning: null
            width: 50
        name: Spacing
        uid: 58dba885-ca9e-483f-a650-4b56929554bc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 21102308-0ca8-4b67-8663-daef265f4c60 # Animation?
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4125615-43a1-4309-9230-e1b85a572c31
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0c9d4adb-358d-4f4a-bc63-c70c2ee59239
            userCondition: null
          -
            elementCondition: null
            fieldUid: 3b2d250a-efd7-4394-9e59-a1ae3b9d5292 # Animation Style
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b30db60-76a8-4faa-aece-0ca811dc1d7c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8df78e11-4ebe-4815-a6a8-a9a62e77b6d6 # Animation Easing
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 704363f4-4beb-42ef-b57d-6f8947ddcc3f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e0e47b5e-62b4-4b02-aeca-99868e8625d9 # Animation Duration
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6128921f-c450-49b3-b631-ec428277d010
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0e13a17a-1829-4ccb-a64f-c39b6d62af82 # Animation Offset
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41fd439a-a804-44e6-b2a4-83eb97a1e152
            userCondition: null
            warning: null
            width: 50
        name: Animation
        uid: 8be1bb07-c86e-4aec-8285-1e0f492801a2
        userCondition: null
handle: infoBox
hasTitleField: false
icon: circle-info
name: 'Info Box'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
