columnSuffix: null
handle: containerBackgroundColor
instructions: null
name: 'Container Background Color'
searchable: false
settings:
  default: null
  palette: 'Container Background Color'
  setRandom: false
  useConfigFile: true
translationKeyFormat: null
translationMethod: none
type: percipiolondon\colourswatches\fields\ColourSwatches
