columnSuffix: null
handle: imageRatio
instructions: null
name: 'Image Ratio'
searchable: false
settings:
  cachedOptions: true
  element: null
  genError: null
  json: ''
  template: _/sdf/imageRatio.json
  templateData: null
translationKeyFormat: null
translationMethod: none
type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
