columnSuffix: null
handle: linearGradientBackgroundColor
instructions: null
name: 'Linear Gradient Background Color'
searchable: false
settings:
  default: null
  palette: 'Linear Gradient Background Color'
  setRandom: false
  useConfigFile: true
translationKeyFormat: null
translationMethod: none
type: percipiolondon\colourswatches\fields\ColourSwatches
