columnSuffix: null
handle: minusMarginTop2
instructions: null
name: 'Minus Margin Top'
searchable: false
settings:
  default: false
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
